-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgCjdU2SGIX6UIrQlE
tU+mFIxUeKBucdDypTjJUtqfHX+gCgYIKoZIzj0DAQehRANCAAQoOQpum21SMhVC
sD47+i9RwA0m8LLuI+yEEUHoT70lruA1kmu1+Glpdt5y44Hd1s+Tb4jbXLOW8XJi
9xhvfFqQ
-----END PRIVATE KEY-----