export const storagePath = 'public/storage';
export const MAX_STRAIGHT_EVENT_TEN_DATE_PARTICIPANTS = 20;
export const MAX_STRAIGHT_EVENT_FIVE_DATE_PARTICIPANTS = 10;
export const MAX_OTHER_EVENT_TEN_DATE_PARTICIPANTS = 11;
export const MAX_OTHER_EVENT_FIVE_DATE_PARTICIPANTS = 6;

export const NOTIFICATION = {
  PRIVATE_MESSAGE: 'PRIVATE_MESSAGE',
  EVENT_REMINDER: 'EVENT_REMINDER',
  LIKE_ACTION: 'LIKE_ACTION',
  MATCH: 'MATCH'
};
